services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 7225067372:AAHJwGF6DE6E4dq9jNkX6Tq7b6ObRQG4BcM
